name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - auth/**

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t thinhvqnguyen/auth:latest .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker image push thinhvqnguyen/auth:latest
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - uses: 'google-github-actions/setup-gcloud@v1'
      - run: gcloud container clusters get-credentials ticketing-dev
      - run: kubectl rollout restart deployment auth-depl

