name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - auth/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd auth && docker build -t thinhvqnguyen/auth:latest .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker image push thinhvqnguyen/auth:latest

      # DEPLOYMENT:
      ### USING DIGITAL OCEAN ###
      - uses: digitalocean/action-doctl@v3
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernets cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl

      ###  USING GOOGLE CLOUD ####
      # - uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      #     service_account: ${{ secrets.SERVICE_ACCOUNT }}
      # - uses: "google-github-actions/setup-gcloud@v1"
      # - run: gcloud container clusters get-credentials ticketing-dev
      # - run: kubectl rollout restart deployment auth-depl
