name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - infra/**

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - uses: 'google-github-actions/setup-gcloud@v1'
      - run: gcloud container clusters get-credentials ticketing-dev
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
